---
title: "Mapping The Impact of Internal Migration Across Europe"
draft: false
author: "Francisco Rowe"
date: '2020-02-08'
categories: ["R"]
tags: ["Spatial Analysis", "Migration", "Spatial Impact", "Europe"]
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
library(leaflet)
library(htmlwidgets)
library(htmltools)
library(widgetframe)
library(leaflet.extras)
knitr::opts_chunk$set(collapse = TRUE)
```

# Net Internal Migration Rate Across Europe

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# read data
rm(list=ls())
load("./data/eu_netmig_map.RData")
```



```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=10,fig.height=7}
# Specify the colour palette
pal <- colorFactor(palette = c("red", "salmon1", "white", "steelblue1", "blue"), 
           levels = c("less than -2", "-2 to 0", "0", "0 to 2", "more than 2"), ordered = FALSE)

# pal <- colorBin("RdYlBu", domain = spdf$z_score, bins = bins)

# There is a list of all the available background tiles in
# http://leaflet-extras.github.io/leaflet-providers/preview/index.html
# Create the initial background map, zooming in Europe
colourmap <- leaflet() %>% 
  addTiles() %>% 
  setView(lat = 48, lng = 20, zoom = 4) %>% 
  addProviderTiles("NASAGIBS.ViirsEarthAtNight2012", group = "Night lights") %>% 
  addProviderTiles("Stamen.TonerLite", group = "Base map")

# Create the interactive map showing the sequence clusters
interactive_map <- colourmap %>%
  addPolygons(data = combined_data_simpl_sf,
              fillColor = ~pal(z_cat),
              weight = 0.4,
              opacity = 0.8,
              color = "black",
              dashArray = "3",
              fillOpacity = 0.7,
              popup = paste("Name: ", combined_data_simpl_sf$name, "<br>",
                            "Net Migration: ", combined_data_simpl_sf$net_migr, "<br>"),
              group = "Net migration rate",
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE)) %>% 
  addLegend(pal = pal,
            values  = combined_data_simpl_sf$z_cat,
            na.label = "Missing data",
            position = "bottomleft",
            title = "Net migration rate (z-scores)") %>% 
  addLayersControl(baseGroups = c("Night lights", "Base map"),
    overlayGroups = "Net migration rate",
    options = layersControlOptions(collapsed = FALSE)) %>% 
  addFullscreenControl()
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
frameWidget(interactive_map, options = frameOptions(allowfullscreen = TRUE))
```
